runtime: python27
threadsafe: true
api_version: 1
instance_class: F1

handlers:
- url: /statics
  static_dir: statics
  secure: always

- url: /admin/(.*)
  script: main.admin
  secure: always
  login: admin

- url: /(.*)
  script: main.app
  secure: always

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest